// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

import { NextIntlClientProvider } from "next-intl";

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        {/*className={`${geistSans.variable} ${geistMono.variable}`} />*/}
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
